-- Sprint 4 (completion): settings storage, so SETTINGS sync jobs have a source
--
-- CREATE/UPDATE/DELETE jobs are generated by writes to `people`. SETTINGS jobs
-- had no equivalent source: there was nowhere for settings to live, so nothing
-- could change and therefore nothing could be pushed. This adds that store.
--
-- Settings are held at the site. Every device at a site inherits them, which is
-- the common case for a terminal fleet (unlock duration, tamper alarm, sync
-- interval). Per-device overrides can be layered on later without changing the
-- job format, because the payload is opaque JSON to the transport.
--
-- `settings_version` increments on every change. It rides along in the job
-- payload so a device applying jobs out of order -- or replaying an old one --
-- can discard settings older than what it already holds. That makes SETTINGS
-- idempotent in the same way CREATE/UPDATE are.

BEGIN;

ALTER TABLE sites ADD COLUMN IF NOT EXISTS settings JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS settings_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS settings_updated_at TIMESTAMP;

ALTER TABLE sites DROP CONSTRAINT IF EXISTS sites_settings_object_check;
ALTER TABLE sites ADD CONSTRAINT sites_settings_object_check
    CHECK (jsonb_typeof(settings) = 'object');

ALTER TABLE sites DROP CONSTRAINT IF EXISTS sites_settings_version_check;
ALTER TABLE sites ADD CONSTRAINT sites_settings_version_check
    CHECK (settings_version > 0);

-- Defaults for existing sites. Deliberately conservative: these mirror the
-- schema defaults already in `doors`, so applying them changes no behaviour.
UPDATE sites
   SET settings = jsonb_build_object(
           'unlock_duration_seconds', 5,
           'sync_interval_seconds', 60,
           'offline_grace_minutes', 60,
           'tamper_alarm', true
       ),
       settings_updated_at = CURRENT_TIMESTAMP
 WHERE settings = '{}'::jsonb;

COMMIT;
