-- ---------------------------------------------------------------------------
-- 013: a general event model, and an operator audit trail
-- ---------------------------------------------------------------------------
--
-- TWO DIFFERENT KINDS OF HISTORY, DELIBERATELY IN TWO TABLES.
--
--   events        what happened in the FIELD. A person presented a credential at
--                 a terminal and something was decided or recorded. Produced by
--                 devices, subject to a person, and the substrate every
--                 application reads and writes.
--
--   audit_events  what an OPERATOR did in the console. Who created a site,
--                 rotated a key, changed a role, deleted a person, enabled a
--                 capability. Produced by humans, subject to configuration.
--
-- Collapsing them sounds tidy and is wrong: they have different subjects,
-- different retention obligations, different access rules, and different
-- volumes by three orders of magnitude. A query for "who was admitted this
-- morning" and a query for "who changed this role" have nothing in common but
-- the word history.
--
-- ---------------------------------------------------------------------------
-- WHY access_logs COULD NOT BE EXTENDED
-- ---------------------------------------------------------------------------
--
-- access_logs records exactly one thing: `granted BOOLEAN`. Every capability
-- beyond opening a door needs something that column cannot say.
--
--   ATTENDANCE       needs a direction. "Present" is not granted-or-denied; it
--                    is an arrival, later paired with a departure.
--   CHECK_IN         needs a subject that is not a door -- an appointment, an
--                    event, a session.
--   VERIFICATION     needs an outcome that is neither. "This person is who they
--                    claim" is a confirmation, and nothing was released.
--   TIME_TRACKING    needs both directions and the pairing between them.
--   VISITOR_MGMT     needs a person who is deliberately not on the roster, and a
--                    host who vouched for them.
--
-- Adding five columns to access_logs would produce a table where most columns
-- are null most of the time and no constraint can say which combinations are
-- valid. The honest shape is a typed event with a small closed set of platform
-- DECISIONS and an open set of application-defined TYPES.
--
-- ---------------------------------------------------------------------------
-- WHY event_type HAS NO CHECK CONSTRAINT
-- ---------------------------------------------------------------------------
--
-- Deliberate, and the opposite of what 009_applications.sql did for capability
-- codes. That migration put the capability list in a CHECK, and the audit found
-- it: adding a capability to a configurable platform then needed a database
-- migration in two places. The lesson applies with more force here, because
-- event types are the thing an application defines.
--
-- Integrity is carried where it belongs instead:
--
--   * `decision` IS constrained, because it is a PLATFORM concept with exactly
--     four meanings and the authorization path branches on it.
--   * `event_type` is validated in Go against a registry applications extend,
--     so a bad value is a 400 rather than a constraint violation the handler
--     cannot distinguish from the database being down.
--   * the format is enforced by CHECK (uppercase, no spaces), because the value
--     travels to firmware and lands in a fixed-width buffer.
--
-- ---------------------------------------------------------------------------
-- IMMUTABILITY
-- ---------------------------------------------------------------------------
--
-- Both tables reject UPDATE and DELETE at the database, not by convention. An
-- audit trail an application can rewrite is not an audit trail, and the
-- application is the thing most likely to try.
--
-- Retention is the deliberate exception and goes through a SECURITY DEFINER
-- function rather than a general DELETE right, so that "delete rows older than
-- the retention window" is expressible and "delete the row that incriminates me"
-- is not.

BEGIN;

-- ---------------------------------------------------------------------------
-- events
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS events (
    id         BIGSERIAL PRIMARY KEY,

    -- THE IDEMPOTENCY KEY, generated by the device. Same contract access_logs
    -- established: a terminal retrying an upload whose response it never heard
    -- must not create a second event. UNIQUE, and the insert is
    -- ON CONFLICT DO NOTHING.
    public_id  UUID NOT NULL DEFAULT gen_random_uuid(),

    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,

    -- Where. All nullable because an event outlives the things that produced it:
    -- a retired site's events remain, and must remain readable.
    site_id    BIGINT REFERENCES sites(id) ON DELETE SET NULL,
    device_id  BIGINT REFERENCES devices(id) ON DELETE SET NULL,

    -- Who. person_id is null for an unrecognised credential, which is the more
    -- interesting half of an audit trail; subject_external_id keeps what the
    -- device actually sent so the attempt is still traceable.
    person_id           BIGINT REFERENCES people(id) ON DELETE SET NULL,
    subject_external_id VARCHAR(64),

    -- Which credential was presented, where the device could say. Null for a
    -- credential that matched nothing, and for events with no credential at all.
    credential_id BIGINT REFERENCES credentials(id) ON DELETE SET NULL,

    -- What. Open by design -- see the note above.
    event_type VARCHAR(40) NOT NULL,

    -- Which capability produced it. Null for platform events that belong to no
    -- application (a terminal coming online, a tamper alarm).
    application VARCHAR(30),

    -- The platform's four outcomes. Closed, because authorization branches here.
    decision VARCHAR(20) NOT NULL DEFAULT 'RECORDED',

    -- WHY, in a machine-readable form. This is the column that makes a denial
    -- actionable rather than mysterious: an operator asking "why was she refused"
    -- gets NO_PERMISSION or OUTSIDE_SCHEDULE or CREDENTIAL_REVOKED, not a
    -- boolean false. Open text for the same reason event_type is.
    reason_code VARCHAR(40),

    -- Attendance and time tracking need the direction; access control does not.
    direction VARCHAR(10),

    -- Application-defined detail. Opaque to the platform, which is what lets a
    -- capability carry what it needs without a migration.
    payload JSONB,

    -- TWO TIMES, AND THE DIFFERENCE MATTERS. occurred_at is when it happened at
    -- the terminal; recorded_at is when the server heard about it. A queued
    -- event uploaded hours later has an occurred_at hours before its
    -- recorded_at, and reporting either as the other would misstate the day's
    -- history.
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Whether the terminal's clock was trustworthy when it stamped occurred_at.
    -- A terminal that has never reached NTP sends nothing and the server stamps
    -- its own arrival time; saying so is more useful than silently presenting a
    -- server time as a door time.
    occurred_at_trusted BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT events_decision_check CHECK (decision IN (
        'GRANTED',   -- something was released
        'DENIED',    -- it was not
        'RECORDED',  -- nothing to release; the event IS the outcome
        'ERROR'      -- the terminal could not decide
    )),

    CONSTRAINT events_direction_check
        CHECK (direction IS NULL OR direction IN ('IN', 'OUT')),

    -- Uppercase, no spaces: these travel to and from firmware.
    CONSTRAINT events_type_format_check
        CHECK (event_type ~ '^[A-Z0-9_]{1,40}$'),
    CONSTRAINT events_reason_format_check
        CHECK (reason_code IS NULL OR reason_code ~ '^[A-Z0-9_]{1,40}$'),
    CONSTRAINT events_application_format_check
        CHECK (application IS NULL OR application ~ '^[A-Z0-9_]{1,30}$'),

    CONSTRAINT events_payload_object_check
        CHECK (payload IS NULL OR jsonb_typeof(payload) = 'object')
);

CREATE UNIQUE INDEX IF NOT EXISTS events_public_id_key ON events(public_id);

-- The console's primary read: one company's recent events, newest first,
-- optionally narrowed to granted sites. company_id leads because it is the
-- tenancy filter every query carries.
CREATE INDEX IF NOT EXISTS idx_events_company_occurred
    ON events(company_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_site_occurred
    ON events(site_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_person_occurred
    ON events(person_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_device_occurred
    ON events(device_id, occurred_at DESC);

-- "Show me denials", which is the query a security review actually runs.
CREATE INDEX IF NOT EXISTS idx_events_company_decision
    ON events(company_id, decision, occurred_at DESC);

-- Per-application reporting: attendance for last month, check-ins today.
CREATE INDEX IF NOT EXISTS idx_events_company_application
    ON events(company_id, application, occurred_at DESC)
    WHERE application IS NOT NULL;

-- Unmatched credentials, for the "who is trying to get in" question.
CREATE INDEX IF NOT EXISTS idx_events_subject_external
    ON events(company_id, subject_external_id)
    WHERE subject_external_id IS NOT NULL;

-- The retention sweep.
CREATE INDEX IF NOT EXISTS idx_events_occurred_at ON events(occurred_at);

-- ---------------------------------------------------------------------------
-- audit_events: what an operator did
-- ---------------------------------------------------------------------------
--
-- Written in the SAME TRANSACTION as the change it describes. An audit row that
-- can be written separately is an audit row that can be missing, and the case
-- where it goes missing is exactly the case somebody is investigating.
--
-- actor_user_id is nullable and the actor's email is DENORMALISED alongside it.
-- Both are deliberate: an operator account can be deleted, and when it is, the
-- record of what they did must survive with enough identity to be readable. A
-- foreign key alone would leave a null and lose the answer.
CREATE TABLE IF NOT EXISTS audit_events (
    id         BIGSERIAL PRIMARY KEY,
    public_id  UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,

    actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    actor_email   VARCHAR(255),
    actor_role    VARCHAR(20),

    -- Where the action came from, for an incident review.
    ip_address VARCHAR(45),
    user_agent VARCHAR(255),
    request_id VARCHAR(64),

    -- VERB_NOUN, e.g. SITE_CREATED, OPERATOR_ROLE_CHANGED, TERMINAL_REVOKED.
    -- Open for the same reason event_type is.
    action VARCHAR(60) NOT NULL,

    -- What was acted on. Type and public id rather than a foreign key per
    -- entity: an audit row must survive the deletion of its subject, and a
    -- column per entity type would be a migration every time one is added.
    target_type      VARCHAR(40),
    target_public_id UUID,
    target_label     VARCHAR(160),

    -- Before and after, where a diff is meaningful. NEVER carries a secret:
    -- the application layer is responsible for redaction, and the columns that
    -- would tempt it -- password hashes, key material -- are not readable from
    -- the paths that write here.
    changes JSONB,

    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT audit_events_action_format_check
        CHECK (action ~ '^[A-Z0-9_]{1,60}$'),
    CONSTRAINT audit_events_changes_object_check
        CHECK (changes IS NULL OR jsonb_typeof(changes) = 'object')
);

CREATE UNIQUE INDEX IF NOT EXISTS audit_events_public_id_key ON audit_events(public_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_company_occurred
    ON audit_events(company_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_actor
    ON audit_events(actor_user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_target
    ON audit_events(target_type, target_public_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_occurred_at
    ON audit_events(occurred_at);

-- ---------------------------------------------------------------------------
-- Immutability, enforced rather than intended
-- ---------------------------------------------------------------------------
--
-- A BEFORE trigger that raises. Applies to every writer including the
-- application's own connection, which is the point -- the application is the
-- thing most likely to try to "correct" an event.
--
-- Retention deletes go through purge_events()/purge_audit_events() below, which
-- set a session flag the trigger honours. That is a narrow, named, auditable
-- exception rather than a general DELETE right.
CREATE OR REPLACE FUNCTION reject_history_mutation()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'DELETE'
       AND current_setting('accesslink.purging', true) = 'on' THEN
        RETURN OLD;
    END IF;

    RAISE EXCEPTION
        '% on % is refused: this is an immutable history table. '
        'Rows are removed only by the retention purge.',
        TG_OP, TG_TABLE_NAME
        USING ERRCODE = 'insufficient_privilege';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS events_immutable ON events;
CREATE TRIGGER events_immutable
    BEFORE UPDATE OR DELETE ON events
    FOR EACH ROW EXECUTE FUNCTION reject_history_mutation();

DROP TRIGGER IF EXISTS audit_events_immutable ON audit_events;
CREATE TRIGGER audit_events_immutable
    BEFORE UPDATE OR DELETE ON audit_events
    FOR EACH ROW EXECUTE FUNCTION reject_history_mutation();

-- ---------------------------------------------------------------------------
-- Retention
-- ---------------------------------------------------------------------------
--
-- Addresses the audit finding that access_logs had no retention policy and was
-- explicitly never pruned -- unbounded growth on the busiest table, and personal
-- data retained indefinitely by design, which is not a posture a customer's data
-- protection officer can sign off.
--
-- Retention is PER COMPANY, because how long a customer must keep access records
-- is their legal question and not the platform's. NULL means "keep for ever",
-- which stays the default: silently deleting a customer's audit history because
-- the platform picked a number would be worse than growth.
ALTER TABLE companies ADD COLUMN IF NOT EXISTS event_retention_days INTEGER;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS audit_retention_days INTEGER;

ALTER TABLE companies DROP CONSTRAINT IF EXISTS companies_event_retention_check;
ALTER TABLE companies ADD CONSTRAINT companies_event_retention_check
    CHECK (event_retention_days IS NULL OR event_retention_days >= 1);

ALTER TABLE companies DROP CONSTRAINT IF EXISTS companies_audit_retention_check;
ALTER TABLE companies ADD CONSTRAINT companies_audit_retention_check
    CHECK (audit_retention_days IS NULL OR audit_retention_days >= 30);

COMMENT ON COLUMN companies.event_retention_days IS
    'Days to retain field events. NULL keeps them indefinitely.';
COMMENT ON COLUMN companies.audit_retention_days IS
    'Days to retain operator audit records. NULL keeps them indefinitely. '
    'Floor of 30 days: an audit trail shorter than an incident review is not one.';

-- The narrow exception to immutability. Deletes only by age, only against a
-- company's own configured window, and reports what it removed.
CREATE OR REPLACE FUNCTION purge_events(p_company_id BIGINT DEFAULT NULL)
RETURNS BIGINT AS $$
DECLARE
    removed BIGINT := 0;
BEGIN
    PERFORM set_config('accesslink.purging', 'on', true);

    WITH expired AS (
        SELECT e.id
          FROM events e
          JOIN companies c ON c.id = e.company_id
         WHERE c.event_retention_days IS NOT NULL
           AND (p_company_id IS NULL OR c.id = p_company_id)
           AND e.occurred_at < CURRENT_TIMESTAMP
                               - make_interval(days => c.event_retention_days)
    )
    DELETE FROM events WHERE id IN (SELECT id FROM expired);

    GET DIAGNOSTICS removed = ROW_COUNT;
    PERFORM set_config('accesslink.purging', 'off', true);
    RETURN removed;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION purge_audit_events(p_company_id BIGINT DEFAULT NULL)
RETURNS BIGINT AS $$
DECLARE
    removed BIGINT := 0;
BEGIN
    PERFORM set_config('accesslink.purging', 'on', true);

    WITH expired AS (
        SELECT a.id
          FROM audit_events a
          JOIN companies c ON c.id = a.company_id
         WHERE c.audit_retention_days IS NOT NULL
           AND (p_company_id IS NULL OR c.id = p_company_id)
           AND a.occurred_at < CURRENT_TIMESTAMP
                               - make_interval(days => c.audit_retention_days)
    )
    DELETE FROM audit_events WHERE id IN (SELECT id FROM expired);

    GET DIAGNOSTICS removed = ROW_COUNT;
    PERFORM set_config('accesslink.purging', 'off', true);
    RETURN removed;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Back-fill: every access_log becomes an event
-- ---------------------------------------------------------------------------
--
-- access_logs is not dropped and not rewritten -- it is an immutable audit trail
-- and this migration will not be the thing that edits one. It stops being
-- WRITTEN once the application layer moves over; the rows stay exactly as they
-- are, and this copies them forward so that the console's history does not begin
-- on the day this migration ran.
--
-- public_id is carried across, which preserves the device-generated idempotency
-- key: a terminal that retries an upload from before this migration still
-- collides correctly against the new table.
INSERT INTO events (public_id, company_id, site_id, device_id, person_id,
                    subject_external_id, event_type, application, decision,
                    direction, occurred_at, recorded_at, occurred_at_trusted)
SELECT al.public_id,
       al.company_id,
       al.site_id,
       al.device_id,
       al.person_id,
       al.person_external_id,
       CASE WHEN al.granted THEN 'ACCESS_GRANTED' ELSE 'ACCESS_DENIED' END,
       'ACCESS_CONTROL',
       CASE WHEN al.granted THEN 'GRANTED' ELSE 'DENIED' END,
       NULL,
       al.occurred_at,
       al.created_at,
       -- Historical rows carry no statement about the terminal's clock, and
       -- claiming one would be inventing evidence.
       FALSE
  FROM access_logs al
ON CONFLICT (public_id) DO NOTHING;

COMMENT ON TABLE access_logs IS
    'SUPERSEDED by events (013_events_and_audit.sql). Retained read-only as the '
    'historical record and as the backing store nothing new is written to. The '
    'legacy /api/v1/access/logs surface is served from events.';

COMMIT;
