package handlers

import (
	"errors"
	"log"
	"net/http"
	"strconv"
	"strings"
	"time"

	"access-terminal-cloud-api/database"
	"access-terminal-cloud-api/middleware"
	"access-terminal-cloud-api/models"

	"github.com/gin-gonic/gin"
)

// Operator authentication endpoints, /api/v1/auth/*.
//
// These are the browser's entry point and they are domain-neutral: nothing here
// knows what the platform is being used for. An operator, a company, a role, a
// set of site grants and a session. Whether that company runs access control,
// attendance, registration or nothing at all is configuration this layer neither
// reads nor cares about.
//
// The site API key appears nowhere in this file. It is the provisioning secret,
// it stays on terminals, and no response below can disclose it.
//
// WHAT LEAVES THE SERVER, AND WHERE. The session token goes into the cookie and
// into nothing else -- it is never in a response body, so a logged response or a
// screenshot of one cannot replay a session. The CSRF token goes into the body
// and never into a cookie, because in a split-origin deployment the dashboard's
// JavaScript cannot read a cookie scoped to the API host.

// sessionResponse is the shape returned by login and by /me.
//
// Both return the SAME body, built by the same function: whatever the dashboard
// gets at login is exactly what it will get on the next reload, so there is no
// second shape to keep in step.
//
// DELIBERATELY AN OBJECT, AND DELIBERATELY EXTENSIBLE. That is what let
// `applications` be added here without breaking a client, and the same holds for
// whatever comes next.
type sessionResponse struct {
	Operator operatorSummary    `json:"operator"`
	Company  companySummary     `json:"company"`
	Role     string             `json:"role"`
	Sites    []models.SiteGrant `json:"sites"`

	// Applications is what this company has enabled, and what the dashboard
	// builds its navigation from. It is the answer to "what is this deployment
	// for", and the platform has no opinion about it: an EMPTY array is a
	// legitimate, common state, not an error and not a reason to fall back to a
	// default set. A console that assumes a workflow when this is empty has
	// reintroduced exactly the single-purpose product this model removed.
	Applications []models.EnabledApplication `json:"applications"`

	// AllSites distinguishes "granted no sites" from "unrestricted". An empty
	// Sites array means the operator is not scoped to particular sites, which
	// is the DEFAULT and means every site in the company -- not none. Without
	// this flag a dashboard could not tell those apart, and would have to guess.
	AllSites bool `json:"all_sites"`

	CSRFToken string `json:"csrf_token"`

	// SessionExpiresAt is computed from the remaining duration the database
	// reported, not passed through from a stored timestamp.
	//
	// That was originally because the stored column was a wall-clock reading
	// mislabelled UTC; migration 010 fixed the column, so forwarding it would
	// now be correct. It is still derived, because deriving it here means the
	// instant is expressed against the clock the RESPONSE was generated by, and
	// the duration beside it stays authoritative. A client that trusts neither
	// clock uses session_expires_in_seconds and is never wrong.
	SessionExpiresAt        time.Time `json:"session_expires_at"`
	SessionExpiresInSeconds int       `json:"session_expires_in_seconds"`
}

// operatorSummary is the operator as the dashboard sees itself. No password
// field of any kind exists on it to leak.
type operatorSummary struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	FullName string `json:"full_name"`
	Role     string `json:"role"`
}

// companySummary names the tenant. Public identifiers only.
type companySummary struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// buildSessionResponse assembles the body login and /me share.
func buildSessionResponse(identity *models.OperatorIdentity,
	grants []models.SiteGrant, applications []models.EnabledApplication) sessionResponse {

	// Empty arrays rather than null: a client should be able to iterate both
	// unconditionally, which is the convention every list endpoint here follows.
	if grants == nil {
		grants = []models.SiteGrant{}
	}
	if applications == nil {
		applications = []models.EnabledApplication{}
	}

	// OWNER and ADMIN reach every site in their company regardless of grants,
	// and so does anyone holding no grants at all. This mirrors exactly what
	// RequireSiteGrant enforces -- if the two ever disagree, the dashboard would
	// offer a site the API then refuses.
	allSites := middleware.RoleAtLeast(identity.Role, models.RoleAdmin) || len(grants) == 0

	return sessionResponse{
		Operator: operatorSummary{
			ID:       identity.UserPublicID,
			Email:    identity.Email,
			FullName: identity.FullName,
			Role:     identity.Role,
		},
		Company: companySummary{
			ID:   identity.CompanyPublicID,
			Name: identity.CompanyName,
			Slug: identity.CompanySlug,
		},
		Role:                    identity.Role,
		Sites:                   grants,
		Applications:            applications,
		AllSites:                allSites,
		CSRFToken:               identity.CSRFToken,
		SessionExpiresAt:        time.Now().UTC().Add(time.Duration(identity.ExpiresInSeconds) * time.Second),
		SessionExpiresInSeconds: identity.ExpiresInSeconds,
	}
}

// setSessionCookie writes the session cookie.
//
// Attributes are not negotiable in production: HttpOnly so no script can read
// it, Secure and Path=/ and no Domain because the __Host- prefix requires all
// three, and SameSite=Lax so it is sent from the dashboard (same site as the
// API) but not from a third party's page.
//
// No Max-Age. The cookie's real lifetime is the row in user_sessions, and an
// expiry the browser enforces independently would only ever be the wrong one.
func setSessionCookie(c *gin.Context, token string) {
	name, secure := middleware.SessionCookieConfig()
	c.SetSameSite(http.SameSiteLaxMode)
	c.SetCookie(name, token, 0, "/", "", secure, true)
}

// clearSessionCookie removes it, with the same attributes it was set with --
// a browser will not replace a cookie whose path or flags do not match.
func clearSessionCookie(c *gin.Context) {
	name, secure := middleware.SessionCookieConfig()
	c.SetSameSite(http.SameSiteLaxMode)
	c.SetCookie(name, "", -1, "/", "", secure, true)
}

// requireJSON rejects a body that did not arrive as JSON.
//
// This is CSRF defence for the one endpoint that cannot have a CSRF token: login
// has no session yet to carry one. An HTML form can be submitted cross-site
// without any script, but it can only send urlencoded, multipart or plain text
// bodies -- it cannot send application/json. Requiring JSON therefore means a
// cross-site login attempt has to come from script, which the browser subjects
// to CORS.
func requireJSON(c *gin.Context) bool {
	if !strings.HasPrefix(c.ContentType(), "application/json") {
		c.JSON(http.StatusUnsupportedMediaType,
			gin.H{"error": "Content-Type must be application/json"})
		return false
	}
	return true
}

// redactEmail keeps a failed login traceable without writing the address into
// the log in full. Enough to correlate repeated attempts, not enough to harvest.
func redactEmail(email string) string {
	at := strings.LastIndex(email, "@")
	if at < 1 {
		return "***"
	}
	return email[:1] + "***" + email[at:]
}

// OperatorLogin handles POST /api/v1/auth/login
//
// Mounted behind the login rate limiter. Unauthenticated by definition, so it is
// the only endpoint in this file with no session in front of it.
//
// Every credential rejection is the same 401 with the same message: unknown
// address, wrong password, disabled account, disabled company. The caller cannot
// act differently on any of them, and telling them apart is how an endpoint
// becomes an account-enumeration oracle. The store also spends one bcrypt
// comparison on an unknown address so the timing does not answer the question
// the message refuses to.
func OperatorLogin(c *gin.Context) {
	if !requireJSON(c) {
		return
	}

	var req models.LoginRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	user, err := database.AuthenticatePassword(req.Email, req.Password)

	var locked *models.AccountLockedError
	switch {
	case errors.As(err, &locked):
		c.Header("Retry-After", strconv.Itoa(locked.RetryAfter()))
		c.JSON(http.StatusTooManyRequests, gin.H{
			"error":       "Too many failed attempts, this account is temporarily locked",
			"retry_after": locked.RetryAfter(),
		})
		return
	case errors.Is(err, models.ErrInvalidCredentials):
		log.Printf("request_id=%s auth=failed email=%s ip=%s",
			middleware.RequestID(c), redactEmail(database.NormalizeEmail(req.Email)), c.ClientIP())
		c.JSON(http.StatusUnauthorized, gin.H{"error": "Invalid email or password"})
		return
	case err != nil:
		logError(c, "authenticate operator", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Authentication unavailable"})
		return
	}

	creds, err := database.CreateSession(user.ID, c.ClientIP(), c.Request.UserAgent())
	if err != nil {
		logError(c, "create operator session", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Authentication unavailable"})
		return
	}

	// Resolve the identity the same way every subsequent request will, rather
	// than assembling it from the login path's own values. It costs one query
	// and guarantees the body returned here is exactly what /me returns next.
	identity, err := database.AuthenticateSession(creds.Token)
	if err != nil || identity == nil {
		logError(c, "resolve new operator session", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Authentication unavailable"})
		return
	}

	grants, applications, ok := loadSessionContext(c, identity, "Authentication unavailable")
	if !ok {
		return
	}

	setSessionCookie(c, creds.Token)
	log.Printf("request_id=%s auth=success operator=%s company=%s ip=%s",
		middleware.RequestID(c), identity.UserPublicID, identity.CompanySlug, c.ClientIP())

	c.JSON(http.StatusOK, buildSessionResponse(identity, grants, applications))
}

// loadSessionContext gathers what the session body needs beyond the identity:
// the operator's site grants and the company's enabled capabilities.
//
// Shared so login and /me cannot answer differently. Reports false once it has
// written an error response.
func loadSessionContext(c *gin.Context, identity *models.OperatorIdentity,
	failureMessage string) ([]models.SiteGrant, []models.EnabledApplication, bool) {

	grants, err := database.ListSiteGrants(identity.UserID)
	if err != nil {
		logError(c, "list operator site grants", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": failureMessage})
		return nil, nil, false
	}

	applications, err := database.EnabledApplications(identity.CompanyID)
	if err != nil {
		logError(c, "list enabled applications", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": failureMessage})
		return nil, nil, false
	}

	return grants, applications, true
}

// OperatorMe handles GET /api/v1/auth/me
//
// The dashboard calls this on load to find out who it is talking as. It returns
// the CSRF token too, which is the reason that token is derived from the session
// token rather than stored: after a page reload the browser still holds the
// cookie but the dashboard has lost its in-memory copy, and without a way to get
// it back it could not make a single unsafe request.
func OperatorMe(c *gin.Context) {
	identity := middleware.Operator(c)
	if identity == nil {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "Authentication required"})
		return
	}

	grants, applications, ok := loadSessionContext(c, identity, "Failed to retrieve session")
	if !ok {
		return
	}

	c.JSON(http.StatusOK, buildSessionResponse(identity, grants, applications))
}

// OperatorLogout handles POST /api/v1/auth/logout
//
// Idempotent, and answers 204 either way. A logout that raced with an expiry
// sweep still succeeded from the caller's point of view, and reporting an error
// would only invite a client to retry something already done.
//
// The cookie is cleared AND the row is revoked. Clearing alone would leave a
// session that anyone holding a copy of the cookie could keep using; revoking
// alone would leave the browser sending a dead cookie on every request.
func OperatorLogout(c *gin.Context) {
	identity := middleware.Operator(c)
	if identity == nil {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "Authentication required"})
		return
	}

	if err := database.RevokeSession(identity.SessionID); err != nil {
		logError(c, "revoke operator session", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to log out"})
		return
	}

	clearSessionCookie(c)
	c.Status(http.StatusNoContent)
}

// OperatorChangePassword handles POST /api/v1/auth/password
//
// Requires the current password even though the caller is already
// authenticated. A session proves someone has the browser, not that they know
// the password, and an unattended machine is exactly the case this guards.
//
// Every OTHER session for this operator is revoked, in the same transaction as
// the change. Someone changing their password usually believes it is known to
// somebody else, and leaving the sessions that password opened alive would make
// the change cosmetic. The current session survives, so the operator is not
// logged out of the tab they are typing in.
//
// Mounted behind the same rate limiter as login, sharing one allowance: the
// current-password check must not become a brute-force surface that login's
// limiter cannot see.
func OperatorChangePassword(c *gin.Context) {
	identity := middleware.Operator(c)
	if identity == nil {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "Authentication required"})
		return
	}
	if !requireJSON(c) {
		return
	}

	var req models.PasswordChangeRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// Validate the new password BEFORE checking the old one, so a caller who
	// sent something the policy would reject learns that without a round trip
	// that also tells them their current password was right.
	if err := database.ValidatePassword(req.NewPassword); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	err := database.VerifyUserPassword(identity.UserID, req.CurrentPassword)
	switch {
	case errors.Is(err, models.ErrInvalidCredentials):
		log.Printf("request_id=%s auth=password-change-rejected operator=%s ip=%s",
			middleware.RequestID(c), identity.UserPublicID, c.ClientIP())
		c.JSON(http.StatusForbidden, gin.H{"error": "Current password is incorrect"})
		return
	case errors.Is(err, models.ErrUserNotFound):
		// The account went away between authenticating and now.
		c.JSON(http.StatusUnauthorized, gin.H{"error": "Invalid or expired session"})
		return
	case err != nil:
		logError(c, "verify operator password", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to change password"})
		return
	}

	if err := database.SetUserPassword(identity.UserID, req.NewPassword, identity.SessionID); err != nil {
		if errors.Is(err, models.ErrPasswordTooShort) || errors.Is(err, models.ErrPasswordTooLong) {
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return
		}
		logError(c, "change operator password", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to change password"})
		return
	}

	log.Printf("request_id=%s auth=password-changed operator=%s ip=%s",
		middleware.RequestID(c), identity.UserPublicID, c.ClientIP())
	c.Status(http.StatusNoContent)
}
