package database

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
	"sync"
	"time"

	"access-terminal-cloud-api/models"

	"github.com/lib/pq"
)

// Integration credentials (migrations/030_api_credentials.sql).
//
// The fourth credential class, and the first one issued to somebody outside the
// company that runs the platform. Everything here is management: issuing,
// listing, rotating, revoking and reporting use. NOTHING IN THIS FILE IS
// REACHED BY A PUBLIC ROUTE, because there is no public route -- authentication
// is implemented and tested (AuthenticateAPICredential) so that the lifecycle
// can be proven before anything depends on it.
//
// THE SECRET EXISTS IN ONE LOCAL VARIABLE. generateAPIKey produces it, the hash
// goes to the database, and the plaintext is returned on the issue path and
// never stored, logged or re-read -- the same discipline generateSiteKey keeps
// for the site provisioning key.
//
// SHA-256 rather than bcrypt, for the reason already written in sites.go: 256
// bits from crypto/rand is not open to dictionary attack, does not need a slow
// KDF, and has to be verifiable on every request without burning CPU.

// HashAPIKey returns the stored form of an integration credential.
//
// Exported because the authentication path hashes what a caller presented before
// looking it up, and that has to be the same function that produced the stored
// value. Two spellings of "the hash" is how an authentication system stops
// authenticating.
func HashAPIKey(key string) string {
	sum := sha256.Sum256([]byte(key))
	return hex.EncodeToString(sum[:])
}

// generateAPIKey returns a new integration credential and its storage form.
//
// 32 bytes from crypto/rand. Not math/rand and not a UUID: a v4 UUID carries 122
// bits and is generated by libraries with varying opinions about entropy
// sources, which is not a thing to be casual about for a credential that reads a
// customer's roster.
func generateAPIKey(environment string) (key, hash, prefix string, err error) {
	if !models.APIEnvironments[environment] {
		return "", "", "", fmt.Errorf("%w: %q", models.ErrUnknownEnvironment, environment)
	}

	raw := make([]byte, 32)
	if _, err := rand.Read(raw); err != nil {
		return "", "", "", fmt.Errorf("generating integration credential: %w", err)
	}

	key = models.APIKeyClassPrefix + environment + "_" + hex.EncodeToString(raw)
	hash = HashAPIKey(key)
	prefix = key[:models.APIKeyPrefixLength] // non-secret, for display
	return key, hash, prefix, nil
}

// ---------------------------------------------------------------------------
// Issue
// ---------------------------------------------------------------------------

// APICredentialIssueInput is what the console supplies to mint one.
type APICredentialIssueInput struct {
	CompanyID int64

	Name        string
	Environment string
	// Scopes must already be expanded and validated by the caller. The store
	// re-checks that every one is known, because the database CHECK would
	// otherwise be the only thing standing between a typo and a stored scope
	// nothing can interpret.
	Scopes []string
	// SitePublicIDs restricts the credential. Empty means every site in the
	// company, now and in future.
	SitePublicIDs []string

	// ExpiresAt nil means never. The caller applies the default lifetime; the
	// store does not invent one, so "never" stays expressible.
	ExpiresAt *time.Time

	ActorUserID int64
	ActorEmail  string
}

// IssueAPICredential mints a credential and returns its plaintext ONCE.
//
// THE PER-COMPANY CAP IS ENFORCED UNDER AN ADVISORY LOCK. PostgreSQL cannot
// express "at most twenty rows per company" as a constraint -- a CHECK cannot
// see other rows and a unique index cannot count -- so two concurrent issues
// could each count nineteen and both insert. pg_advisory_xact_lock serialises
// the count-and-insert for one company and is released by the commit, so the
// window does not exist. Namespace 30 is this migration's number, so the lock
// cannot collide with an unrelated advisory lock taken elsewhere later.
//
// THE COUNT EXCLUDES SUPERSEDED ROWS. A credential in its rotation grace window
// still authenticates but does not occupy a slot, so a company at the cap can
// still rotate. A cap that deadlocks the operation somebody reaches for during
// an incident is worse than no cap.
func IssueAPICredential(in APICredentialIssueInput) (*models.APICredentialIssued, error) {
	for _, scope := range in.Scopes {
		if !models.KnownScope(scope) {
			return nil, fmt.Errorf("%w: %q", models.ErrUnknownScope, scope)
		}
	}
	if len(in.Scopes) == 0 {
		return nil, models.ErrNoScopes
	}

	name, err := models.ValidateAPICredentialName(in.Name)
	if err != nil {
		return nil, err
	}

	if in.ExpiresAt != nil && !in.ExpiresAt.After(time.Now()) {
		return nil, models.ErrAPICredentialExpiryInPast
	}

	key, hash, prefix, err := generateAPIKey(in.Environment)
	if err != nil {
		return nil, err
	}

	tx, err := DB.Begin()
	if err != nil {
		return nil, fmt.Errorf("issuing integration credential: %w", err)
	}
	defer tx.Rollback()

	if err := lockCompanyCredentials(tx, in.CompanyID); err != nil {
		return nil, err
	}

	if err := assertCredentialHeadroom(tx, in.CompanyID); err != nil {
		return nil, err
	}

	siteIDs, err := resolveCredentialSites(tx, in.CompanyID, in.SitePublicIDs)
	if err != nil {
		return nil, err
	}

	var id int64
	err = tx.QueryRow(`
		INSERT INTO api_credentials
		    (company_id, name, environment, key_hash, key_prefix, scopes,
		     created_by, created_by_email, expires_at)
		VALUES ($1, $2, $3, $4, $5, $6,
		        NULLIF($7, 0)::bigint, NULLIF($8, ''), $9)
		RETURNING id`,
		in.CompanyID, name, in.Environment, hash, prefix, pq.Array(in.Scopes),
		in.ActorUserID, in.ActorEmail, in.ExpiresAt).Scan(&id)
	if err != nil {
		if isUniqueViolation(err, "api_credentials_company_name_live") {
			return nil, models.ErrAPICredentialNameTaken
		}
		return nil, fmt.Errorf("inserting integration credential: %w", err)
	}

	if err := attachCredentialSites(tx, id, siteIDs); err != nil {
		return nil, err
	}

	credential, err := loadCredentialTx(tx, in.CompanyID, id)
	if err != nil {
		return nil, err
	}

	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("committing integration credential: %w", err)
	}

	return &models.APICredentialIssued{
		APICredential: *credential,
		Secret:        key,
		ShownOnce:     true,
	}, nil
}

// lockCompanyCredentials serialises credential mutation for one company.
//
// Two integers rather than one bigint so the namespace is explicit and this lock
// cannot be confused with an unrelated one taken on the same company id
// elsewhere. Released by the transaction, so nothing has to remember to unlock.
func lockCompanyCredentials(tx *sql.Tx, companyID int64) error {
	if _, err := tx.Exec(`SELECT pg_advisory_xact_lock(30, $1::int)`, companyID); err != nil {
		return fmt.Errorf("locking company credentials: %w", err)
	}
	return nil
}

// assertCredentialHeadroom refuses a company that is already at the cap.
func assertCredentialHeadroom(tx *sql.Tx, companyID int64) error {
	var live int
	err := tx.QueryRow(`
		SELECT count(*) FROM api_credentials
		 WHERE company_id = $1
		   AND revoked_at IS NULL
		   AND superseded_at IS NULL`, companyID).Scan(&live)
	if err != nil {
		return fmt.Errorf("counting integration credentials: %w", err)
	}
	if live >= models.MaxAPICredentialsPerCompany {
		return models.ErrAPICredentialLimit
	}
	return nil
}

// resolveCredentialSites turns site public ids into row ids, INSIDE the company.
//
// A site in another company does not resolve, and the error says the site is not
// in this company rather than that it does not exist -- the caller is an
// authenticated ADMIN of this tenant, so there is nothing to conceal from them
// about their own account, and a vaguer message would send them looking for a
// typo in an id that is real.
func resolveCredentialSites(tx *sql.Tx, companyID int64, publicIDs []string) ([]int64, error) {
	if len(publicIDs) == 0 {
		return nil, nil
	}

	cleaned := make([]string, 0, len(publicIDs))
	for _, id := range publicIDs {
		if trimmed := strings.TrimSpace(id); trimmed != "" {
			cleaned = append(cleaned, trimmed)
		}
	}
	if len(cleaned) == 0 {
		return nil, nil
	}

	rows, err := tx.Query(`
		SELECT id FROM sites
		 WHERE company_id = $1
		   AND deleted_at IS NULL
		   AND public_id::text = ANY($2)`, companyID, pq.Array(cleaned))
	if err != nil {
		// A malformed UUID reaches here as a cast error rather than as no rows.
		// It is the same answer either way: a site the caller named is not one
		// of theirs.
		return nil, models.ErrAPICredentialSiteUnknown
	}
	defer rows.Close()

	var ids []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, fmt.Errorf("resolving credential sites: %w", err)
		}
		ids = append(ids, id)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("resolving credential sites: %w", err)
	}

	// Every named site must have resolved. Silently dropping one would produce a
	// credential scoped more narrowly than the operator believes, which is the
	// direction that fails closed but still lies to them.
	if len(ids) != len(dedupe(cleaned)) {
		return nil, models.ErrAPICredentialSiteUnknown
	}
	return ids, nil
}

func dedupe(values []string) []string {
	seen := make(map[string]bool, len(values))
	out := make([]string, 0, len(values))
	for _, v := range values {
		if !seen[v] {
			seen[v] = true
			out = append(out, v)
		}
	}
	return out
}

func attachCredentialSites(tx *sql.Tx, credentialID int64, siteIDs []int64) error {
	for _, siteID := range siteIDs {
		if _, err := tx.Exec(`
			INSERT INTO api_credential_sites (credential_id, site_id)
			VALUES ($1, $2) ON CONFLICT DO NOTHING`, credentialID, siteID); err != nil {
			return fmt.Errorf("attaching credential site: %w", err)
		}
	}
	return nil
}

// ---------------------------------------------------------------------------
// Read
// ---------------------------------------------------------------------------

const credentialColumns = `
	c.id, c.public_id, c.name, c.environment, c.key_prefix, c.scopes,
	c.created_by_email, c.created_at, c.expires_at,
	c.last_used_at, c.last_used_ip,
	c.superseded_at, c.grace_expires_at,
	c.revoked_at, c.revoked_reason,
	(SELECT u.email FROM users u WHERE u.id = c.revoked_by),
	(SELECT s.public_id::text FROM api_credentials s WHERE s.id = c.superseded_by)`

type credentialScan struct {
	id             int64
	publicID       string
	name           string
	environment    string
	keyPrefix      string
	scopes         pq.StringArray
	createdByEmail sql.NullString
	createdAt      time.Time
	expiresAt      sql.NullTime
	lastUsedAt     sql.NullTime
	lastUsedIP     sql.NullString
	supersededAt   sql.NullTime
	graceExpiresAt sql.NullTime
	revokedAt      sql.NullTime
	revokedReason  sql.NullString
	revokedByEmail sql.NullString
	supersededBy   sql.NullString
}

func (s *credentialScan) targets() []any {
	return []any{
		&s.id, &s.publicID, &s.name, &s.environment, &s.keyPrefix, &s.scopes,
		&s.createdByEmail, &s.createdAt, &s.expiresAt,
		&s.lastUsedAt, &s.lastUsedIP,
		&s.supersededAt, &s.graceExpiresAt,
		&s.revokedAt, &s.revokedReason,
		&s.revokedByEmail, &s.supersededBy,
	}
}

// credentialStatus resolves the lifecycle state a console renders.
//
// COMPUTED, NOT STORED. Four nullable timestamps describe the state between
// them, and a console asked to combine them is a console that will get it wrong
// once. The precedence is fixed here and is the same precedence the
// authentication predicate applies: revoked beats expired beats grace.
func credentialStatus(s *credentialScan, now time.Time) string {
	switch {
	case s.revokedAt.Valid:
		return models.APICredentialRevokedS
	case s.expiresAt.Valid && !s.expiresAt.Time.After(now):
		return models.APICredentialExpired
	case s.supersededAt.Valid:
		if s.graceExpiresAt.Valid && s.graceExpiresAt.Time.After(now) {
			return models.APICredentialInGrace
		}
		// Past its grace window. Not revoked and not expired, but it no longer
		// authenticates, and reporting it as ACTIVE would be a lie an operator
		// would act on.
		return models.APICredentialExpired
	default:
		return models.APICredentialActive
	}
}

func (s *credentialScan) toModel(now time.Time) *models.APICredential {
	out := &models.APICredential{
		ID:          s.publicID,
		Name:        s.name,
		Environment: s.environment,
		KeyPrefix:   s.keyPrefix,
		Scopes:      []string(s.scopes),
		Sites:       []models.SiteGrant{},
		AllSites:    true,
		CreatedAt:   s.createdAt,
		Status:      credentialStatus(s, now),
	}
	if s.scopes == nil {
		out.Scopes = []string{}
	}
	if s.createdByEmail.Valid {
		out.CreatedByEmail = s.createdByEmail.String
	}
	if s.expiresAt.Valid {
		out.ExpiresAt = &s.expiresAt.Time
	}
	if s.lastUsedAt.Valid {
		out.LastUsedAt = &s.lastUsedAt.Time
	}
	if s.lastUsedIP.Valid {
		out.LastUsedIP = s.lastUsedIP.String
	}
	if s.supersededAt.Valid {
		out.SupersededAt = &s.supersededAt.Time
	}
	if s.graceExpiresAt.Valid {
		out.GraceExpiresAt = &s.graceExpiresAt.Time
	}
	if s.revokedAt.Valid {
		out.RevokedAt = &s.revokedAt.Time
	}
	if s.revokedReason.Valid {
		out.RevokedReason = s.revokedReason.String
	}
	if s.revokedByEmail.Valid {
		out.RevokedByEmail = s.revokedByEmail.String
	}
	if s.supersededBy.Valid {
		out.SupersededByID = s.supersededBy.String
	}
	return out
}

// queryable is the subset of *sql.DB and *sql.Tx these readers need, so one
// implementation serves both a plain read and a read inside a transaction.
type queryable interface {
	Query(query string, args ...any) (*sql.Rows, error)
	QueryRow(query string, args ...any) *sql.Row
	Exec(query string, args ...any) (sql.Result, error)
}

// ListAPICredentials returns every credential in a company, newest first.
//
// Revoked and superseded rows are INCLUDED. "What integrations has this company
// ever had, and what happened to them" is the question an operator asks during a
// review, and a list that hid the revoked ones would answer a different one. The
// status field says which is which.
func ListAPICredentials(companyID int64) (*models.APICredentialList, error) {
	rows, err := DB.Query(`
		SELECT `+credentialColumns+`
		  FROM api_credentials c
		 WHERE c.company_id = $1
		 ORDER BY c.created_at DESC, c.id DESC`, companyID)
	if err != nil {
		return nil, fmt.Errorf("listing integration credentials: %w", err)
	}
	defer rows.Close()

	now := time.Now()
	out := &models.APICredentialList{Credentials: []models.APICredential{}}
	ids := []int64{}
	byID := map[int64]*models.APICredential{}

	for rows.Next() {
		var s credentialScan
		if err := rows.Scan(s.targets()...); err != nil {
			return nil, fmt.Errorf("scanning integration credential: %w", err)
		}
		credential := s.toModel(now)
		out.Credentials = append(out.Credentials, *credential)
		ids = append(ids, s.id)
		byID[s.id] = &out.Credentials[len(out.Credentials)-1]
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("listing integration credentials: %w", err)
	}

	if err := attachSiteGrants(DB, ids, byID); err != nil {
		return nil, err
	}

	out.Count = len(out.Credentials)
	return out, nil
}

// attachSiteGrants fills in the site restriction for a set of credentials.
//
// One query for the whole page rather than one per row: a console listing twenty
// credentials should not make twenty-one round trips, and the join is trivial.
func attachSiteGrants(q queryable, ids []int64, byID map[int64]*models.APICredential) error {
	if len(ids) == 0 {
		return nil
	}

	rows, err := q.Query(`
		SELECT acs.credential_id, s.public_id::text, s.site_name
		  FROM api_credential_sites acs
		  JOIN sites s ON s.id = acs.site_id
		 WHERE acs.credential_id = ANY($1)
		 ORDER BY s.site_name`, pq.Array(ids))
	if err != nil {
		return fmt.Errorf("reading credential site grants: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		var credentialID int64
		var grant models.SiteGrant
		if err := rows.Scan(&credentialID, &grant.SitePublicID, &grant.SiteName); err != nil {
			return fmt.Errorf("scanning credential site grant: %w", err)
		}
		if credential, ok := byID[credentialID]; ok {
			credential.Sites = append(credential.Sites, grant)
			credential.AllSites = false
		}
	}
	return rows.Err()
}

// GetAPICredential reads one credential inside a company.
func GetAPICredential(companyID int64, publicID string) (*models.APICredential, error) {
	return loadCredentialByPublicID(DB, companyID, publicID)
}

func loadCredentialByPublicID(q queryable, companyID int64, publicID string) (*models.APICredential, error) {
	id, err := credentialRowID(q, companyID, publicID)
	if err != nil {
		return nil, err
	}
	return loadCredential(q, companyID, id)
}

// credentialRowID resolves a public id INSIDE a company.
//
// Scoped by company in the same query rather than resolved and then checked:
// one query, one authorization, and no window in which the two can disagree.
// A credential in another company is ErrAPICredentialNotFound, exactly as one
// that never existed.
func credentialRowID(q queryable, companyID int64, publicID string) (int64, error) {
	trimmed := strings.TrimSpace(publicID)
	if trimmed == "" {
		return 0, models.ErrAPICredentialNotFound
	}

	var id int64
	err := q.QueryRow(`
		SELECT id FROM api_credentials
		 WHERE company_id = $1 AND public_id::text = $2`, companyID, trimmed).Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, models.ErrAPICredentialNotFound
	}
	if err != nil {
		// A malformed UUID fails the cast rather than missing. Same answer: the
		// caller named something that is not one of their credentials.
		return 0, models.ErrAPICredentialNotFound
	}
	return id, nil
}

func loadCredential(q queryable, companyID, id int64) (*models.APICredential, error) {
	var s credentialScan
	err := q.QueryRow(`
		SELECT `+credentialColumns+`
		  FROM api_credentials c
		 WHERE c.company_id = $1 AND c.id = $2`, companyID, id).Scan(s.targets()...)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, models.ErrAPICredentialNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("reading integration credential: %w", err)
	}

	credential := s.toModel(time.Now())
	byID := map[int64]*models.APICredential{s.id: credential}
	if err := attachSiteGrants(q, []int64{s.id}, byID); err != nil {
		return nil, err
	}
	return credential, nil
}

func loadCredentialTx(tx *sql.Tx, companyID, id int64) (*models.APICredential, error) {
	return loadCredential(tx, companyID, id)
}

// ---------------------------------------------------------------------------
// Rotate
// ---------------------------------------------------------------------------

// RotateAPICredential supersedes a credential and issues its replacement.
//
// A NEW ROW, NOT A NEW HASH ON THE OLD ONE. The integrator needs an overlap in
// which to deploy; replacing the hash in place forces a simultaneous cutover
// that will be done badly at two in the morning. Both credentials authenticate
// until grace_expires_at, and a grace of zero is an immediate cutover -- which
// is the right choice when the reason for rotating is that the old one leaked.
//
// The name, scopes, environment and site restriction are carried over. Changing
// what an integration may do is a separate decision from replacing its secret,
// and bundling the two would mean an emergency rotation is also an opportunity
// to fat-finger a scope.
func RotateAPICredential(companyID int64, publicID string, grace time.Duration,
	actorUserID int64, actorEmail string) (*models.APICredentialIssued, error) {

	if grace < 0 {
		grace = 0
	}
	if grace > models.MaxAPIKeyRotationGrace {
		return nil, models.ErrAPIKeyGraceTooLong
	}

	tx, err := DB.Begin()
	if err != nil {
		return nil, fmt.Errorf("rotating integration credential: %w", err)
	}
	defer tx.Rollback()

	if err := lockCompanyCredentials(tx, companyID); err != nil {
		return nil, err
	}

	oldID, err := credentialRowID(tx, companyID, publicID)
	if err != nil {
		return nil, err
	}

	var (
		name         string
		environment  string
		scopes       pq.StringArray
		expiresAt    sql.NullTime
		revokedAt    sql.NullTime
		supersededAt sql.NullTime
	)
	err = tx.QueryRow(`
		SELECT name, environment, scopes, expires_at, revoked_at, superseded_at
		  FROM api_credentials
		 WHERE company_id = $1 AND id = $2
		 FOR UPDATE`, companyID, oldID).
		Scan(&name, &environment, &scopes, &expiresAt, &revokedAt, &supersededAt)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, models.ErrAPICredentialNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("reading credential for rotation: %w", err)
	}

	if revokedAt.Valid {
		return nil, models.ErrAPICredentialRevoked
	}
	// Rotating an already-superseded row would branch the chain and leave two
	// replacements for one original, with nothing to say which is current.
	if supersededAt.Valid {
		return nil, models.ErrAPICredentialSuperseded
	}

	key, hash, prefix, err := generateAPIKey(environment)
	if err != nil {
		return nil, err
	}

	// ORDER MATTERS. The old row leaves api_credentials_company_name_live as
	// soon as superseded_at is set, which is what lets the replacement enter the
	// index under the same name inside this transaction.
	graceExpiry := time.Now().Add(grace)
	if _, err := tx.Exec(`
		UPDATE api_credentials
		   SET superseded_at = CURRENT_TIMESTAMP, grace_expires_at = $3
		 WHERE company_id = $1 AND id = $2`, companyID, oldID, graceExpiry); err != nil {
		return nil, fmt.Errorf("superseding integration credential: %w", err)
	}

	var newID int64
	err = tx.QueryRow(`
		INSERT INTO api_credentials
		    (company_id, name, environment, key_hash, key_prefix, scopes,
		     created_by, created_by_email, expires_at)
		VALUES ($1, $2, $3, $4, $5, $6,
		        NULLIF($7, 0)::bigint, NULLIF($8, ''), $9)
		RETURNING id`,
		companyID, name, environment, hash, prefix, scopes,
		actorUserID, actorEmail, nullTime(expiresAt)).Scan(&newID)
	if err != nil {
		return nil, fmt.Errorf("inserting rotated credential: %w", err)
	}

	if _, err := tx.Exec(`
		UPDATE api_credentials SET superseded_by = $3
		 WHERE company_id = $1 AND id = $2`, companyID, oldID, newID); err != nil {
		return nil, fmt.Errorf("linking rotated credential: %w", err)
	}

	// The site restriction is part of what the credential IS, so it moves with
	// the name and the scopes.
	if _, err := tx.Exec(`
		INSERT INTO api_credential_sites (credential_id, site_id)
		SELECT $2, site_id FROM api_credential_sites WHERE credential_id = $1`,
		oldID, newID); err != nil {
		return nil, fmt.Errorf("copying credential sites: %w", err)
	}

	credential, err := loadCredentialTx(tx, companyID, newID)
	if err != nil {
		return nil, err
	}

	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("committing credential rotation: %w", err)
	}

	return &models.APICredentialIssued{
		APICredential: *credential,
		Secret:        key,
		ShownOnce:     true,
	}, nil
}

func nullTime(t sql.NullTime) any {
	if !t.Valid {
		return nil
	}
	return t.Time
}

// ---------------------------------------------------------------------------
// Revoke
// ---------------------------------------------------------------------------

// RevokeAPICredential withdraws one credential permanently.
//
// Effective on the next request: the authentication path reads the row every
// time and nothing caches it, so there is no window in which a revoked
// credential still works. The row is kept, because the audit trail references
// it and because "what did this integration do before we turned it off" is the
// question somebody asks immediately afterwards.
func RevokeAPICredential(companyID int64, publicID, reason string,
	actorUserID int64) (*models.APICredential, error) {

	trimmed := strings.TrimSpace(reason)
	if trimmed == "" {
		trimmed = "revoked from the console"
	}
	if len(trimmed) > models.MaxAPICredentialReasonLength {
		trimmed = trimmed[:models.MaxAPICredentialReasonLength]
	}

	id, err := credentialRowID(DB, companyID, publicID)
	if err != nil {
		return nil, err
	}

	result, err := DB.Exec(`
		UPDATE api_credentials
		   SET revoked_at = CURRENT_TIMESTAMP,
		       revoked_by = NULLIF($3, 0)::bigint,
		       revoked_reason = $4
		 WHERE company_id = $1 AND id = $2 AND revoked_at IS NULL`,
		companyID, id, actorUserID, trimmed)
	if err != nil {
		return nil, fmt.Errorf("revoking integration credential: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return nil, fmt.Errorf("revoking integration credential: %w", err)
	}
	if affected == 0 {
		// The row exists -- credentialRowID found it -- so the only way to
		// affect nothing is that it was already revoked. Idempotent would be
		// defensible; saying so is more useful, because a second revocation is
		// usually somebody unsure whether the first one worked.
		return nil, models.ErrAPICredentialRevoked
	}

	return loadCredential(DB, companyID, id)
}

// RevokeAllAPICredentials withdraws every live credential in a company.
//
// THE INCIDENT-RESPONSE CONTROL. One transaction, one audit record, one number
// to report. It matches rows that can still authenticate -- not revoked --
// including ones inside a rotation grace window, because "turn off every
// integration" must not leave the half of a rotation nobody was thinking about
// still working.
func RevokeAllAPICredentials(companyID int64, reason string, actorUserID int64) (int, error) {
	trimmed := strings.TrimSpace(reason)
	if trimmed == "" {
		trimmed = "bulk revocation from the console"
	}
	if len(trimmed) > models.MaxAPICredentialReasonLength {
		trimmed = trimmed[:models.MaxAPICredentialReasonLength]
	}

	result, err := DB.Exec(`
		UPDATE api_credentials
		   SET revoked_at = CURRENT_TIMESTAMP,
		       revoked_by = NULLIF($2, 0)::bigint,
		       revoked_reason = $3
		 WHERE company_id = $1 AND revoked_at IS NULL`,
		companyID, actorUserID, trimmed)
	if err != nil {
		return 0, fmt.Errorf("revoking integration credentials: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("revoking integration credentials: %w", err)
	}
	return int(affected), nil
}

// ---------------------------------------------------------------------------
// Authentication
// ---------------------------------------------------------------------------

// AuthenticateAPICredential resolves a presented credential.
//
// NO ROUTE CALLS THIS YET. It exists in P1 so that the lifecycle above can be
// proven -- that a revoked credential stops working, that an expired one does,
// that a superseded one works until its grace window closes and not after -- by
// a test rather than by an assertion in a comment. The middleware that will use
// it belongs with the public routes, which do not exist.
//
// environment is the DEPLOYMENT's environment. A credential minted for the other
// one is refused by shape, before the database is touched: a staging key that
// reached production must fail immediately rather than miss a lookup and look
// like a typo.
//
// A DATABASE FAILURE IS NOT AN INVALID CREDENTIAL. It returns an error, and the
// caller must report it as a server fault -- the same reasoning AuthMiddleware
// applies to site keys and OperatorAuthMiddleware to sessions. Telling a caller
// its credential is invalid during an outage sends somebody looking for a
// credential problem that does not exist.
func AuthenticateAPICredential(presented, environment string) (*models.APICredentialIdentity, error) {
	if !models.ValidAPIKeyShape(presented) {
		return nil, nil
	}
	if models.APIKeyEnvironment(presented) != environment {
		return nil, nil
	}

	var (
		identity models.APICredentialIdentity
		scopes   pq.StringArray
	)
	err := DB.QueryRow(`
		SELECT c.id, c.public_id::text, c.company_id, c.name, c.key_prefix,
		       c.environment, c.scopes
		  FROM api_credentials c
		  JOIN companies co ON co.id = c.company_id
		 WHERE c.key_hash = $1
		   AND c.revoked_at IS NULL
		   AND (c.expires_at IS NULL OR c.expires_at > CURRENT_TIMESTAMP)
		   AND (c.superseded_at IS NULL OR c.grace_expires_at > CURRENT_TIMESTAMP)
		   AND co.active
		   AND co.deleted_at IS NULL`, HashAPIKey(presented)).
		Scan(&identity.ID, &identity.PublicID, &identity.CompanyID, &identity.Name,
			&identity.KeyPrefix, &identity.Environment, &scopes)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("authenticating integration credential: %w", err)
	}

	identity.Scopes = []string(scopes)

	siteIDs, err := credentialSiteIDs(identity.ID)
	if err != nil {
		return nil, err
	}
	identity.SiteIDs = siteIDs

	return &identity, nil
}

// credentialSiteIDs reads the site restriction. No rows means the whole company.
func credentialSiteIDs(credentialID int64) ([]int64, error) {
	rows, err := DB.Query(
		`SELECT site_id FROM api_credential_sites WHERE credential_id = $1`, credentialID)
	if err != nil {
		return nil, fmt.Errorf("reading credential sites: %w", err)
	}
	defer rows.Close()

	var ids []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, fmt.Errorf("scanning credential site: %w", err)
		}
		ids = append(ids, id)
	}
	return ids, rows.Err()
}

// ---------------------------------------------------------------------------
// Usage telemetry
// ---------------------------------------------------------------------------
//
// LAST-USED IS NOT WRITTEN ON THE REQUEST PATH. A read-only API that writes a
// row to record that it was read has doubled its write load to store a value
// nobody reads in real time. Uses are accumulated in memory and flushed by the
// maintenance scheduler, so the cost is one statement per flush rather than one
// per request.
//
// NOTHING HERE CAN FAIL A REQUEST. NoteAPICredentialUse touches no database at
// all; a flush that fails is logged and retried on the next tick. That is the
// same trade WriteAuditEvent already makes, for the same reason: telemetry that
// takes the product down is telemetry somebody disables.

type credentialUse struct {
	at    time.Time
	ip    string
	byDay map[string]map[string]*usageCount // day -> class -> counts
}

type usageCount struct {
	requests int64
	refusals int64
}

var (
	credentialUseMu sync.Mutex
	credentialUses  = map[int64]*credentialUse{}
)

// NoteAPICredentialUse records that a credential served a request.
//
// refused says whether the request was turned away by the rate limiter; both are
// counted, because "this key is being refused constantly" is as useful an
// answer as "this key is busy".
func NoteAPICredentialUse(credentialID int64, ip, class string, at time.Time, refused bool) {
	if credentialID == 0 {
		return
	}

	credentialUseMu.Lock()
	defer credentialUseMu.Unlock()

	use, ok := credentialUses[credentialID]
	if !ok {
		use = &credentialUse{byDay: map[string]map[string]*usageCount{}}
		credentialUses[credentialID] = use
	}
	if at.After(use.at) {
		use.at = at
		if ip != "" {
			use.ip = ip
		}
	}

	if class == "" {
		return
	}
	day := at.UTC().Format("2006-01-02")
	classes, ok := use.byDay[day]
	if !ok {
		classes = map[string]*usageCount{}
		use.byDay[day] = classes
	}
	count, ok := classes[class]
	if !ok {
		count = &usageCount{}
		classes[class] = count
	}
	if refused {
		count.refusals++
	} else {
		count.requests++
	}
}

// FlushAPICredentialUse writes accumulated telemetry.
//
// Drains the buffer under the lock and writes outside it, so a slow database
// does not block the request path that is still recording uses.
func FlushAPICredentialUse(ctx context.Context) (int, error) {
	credentialUseMu.Lock()
	pending := credentialUses
	credentialUses = map[int64]*credentialUse{}
	credentialUseMu.Unlock()

	if len(pending) == 0 {
		return 0, nil
	}

	written := 0
	for credentialID, use := range pending {
		if !use.at.IsZero() {
			// GREATEST, so an out-of-order flush cannot move last_used_at
			// backwards. Two instances flushing concurrently is the normal case
			// once there is more than one.
			if _, err := DB.ExecContext(ctx, `
				UPDATE api_credentials
				   SET last_used_at = GREATEST(COALESCE(last_used_at, $2), $2),
				       last_used_ip = COALESCE(NULLIF($3, ''), last_used_ip)
				 WHERE id = $1`, credentialID, use.at, use.ip); err != nil {
				return written, fmt.Errorf("flushing credential use: %w", err)
			}
			written++
		}

		for day, classes := range use.byDay {
			for class, count := range classes {
				if _, err := DB.ExecContext(ctx, `
					INSERT INTO api_usage_daily (credential_id, day, class, requests, refusals)
					VALUES ($1, $2::date, $3, $4, $5)
					ON CONFLICT (credential_id, day, class) DO UPDATE
					   SET requests = api_usage_daily.requests + EXCLUDED.requests,
					       refusals = api_usage_daily.refusals + EXCLUDED.refusals`,
					credentialID, day, class, count.requests, count.refusals); err != nil {
					return written, fmt.Errorf("flushing credential usage: %w", err)
				}
			}
		}
	}
	return written, nil
}

// GetAPICredentialUsage reports recent use of one credential.
func GetAPICredentialUsage(companyID int64, publicID string, days int) (*models.APICredentialUsage, error) {
	if days <= 0 || days > 365 {
		days = 30
	}

	id, err := credentialRowID(DB, companyID, publicID)
	if err != nil {
		return nil, err
	}

	out := &models.APICredentialUsage{Days: []models.APICredentialUsageDay{}}

	var lastUsedAt sql.NullTime
	var lastUsedIP sql.NullString
	if err := DB.QueryRow(`
		SELECT public_id::text, name, key_prefix, last_used_at, last_used_ip
		  FROM api_credentials WHERE company_id = $1 AND id = $2`, companyID, id).
		Scan(&out.ID, &out.Name, &out.KeyPrefix, &lastUsedAt, &lastUsedIP); err != nil {
		return nil, fmt.Errorf("reading credential usage: %w", err)
	}
	if lastUsedAt.Valid {
		out.LastUsedAt = &lastUsedAt.Time
	}
	if lastUsedIP.Valid {
		out.LastUsedIP = lastUsedIP.String
	}

	rows, err := DB.Query(`
		SELECT to_char(day, 'YYYY-MM-DD'), class, requests, refusals
		  FROM api_usage_daily
		 WHERE credential_id = $1
		   AND day >= (CURRENT_DATE - $2::int)
		 ORDER BY day DESC, class`, id, days)
	if err != nil {
		return nil, fmt.Errorf("reading credential usage: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		var d models.APICredentialUsageDay
		if err := rows.Scan(&d.Day, &d.Class, &d.Requests, &d.Refusals); err != nil {
			return nil, fmt.Errorf("scanning credential usage: %w", err)
		}
		out.Days = append(out.Days, d)
	}
	return out, rows.Err()
}

// isUniqueViolation reports whether err is a unique index violation on the named
// constraint.
//
// Matching on the CONSTRAINT NAME rather than on the message text: the message
// is localised and version-dependent, and a substring match on it is how an
// error handler quietly stops recognising the case it was written for.
func isUniqueViolation(err error, constraint string) bool {
	var pqErr *pq.Error
	if !errors.As(err, &pqErr) {
		return false
	}
	return pqErr.Code == "23505" && pqErr.Constraint == constraint
}
