package database

import (
	"crypto/rand"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"

	"access-terminal-cloud-api/models"
)

// Site lifecycle: creation, metadata, retirement, and the provisioning key.
//
// THE CREDENTIAL IS THE POINT OF THIS FILE. A site API key registers terminals
// and rotates their device credentials, which makes it the highest-value secret
// in the system -- higher than any single device key, because it mints them.
// Since 011_site_credentials.sql it is stored as a SHA-256 hash and exists in
// plaintext exactly twice: in the response that creates or rotates it, and in
// whatever the operator does with it next. There is no path that reads one back
// out of the database, because there is nothing to read.
//
// SHA-256 rather than bcrypt, matching devices: 256 bits from crypto/rand is not
// open to dictionary attack and does not need a slow KDF, and it has to be
// verifiable on every device poll without burning CPU.

// siteKeyPrefix marks a site provisioning key, as atd_ marks a device key.
// Distinguishing the two by sight matters when one is pasted where the other
// belongs.
const siteKeyPrefix = "ats_"

// generateSiteKey returns a new provisioning credential and its storage form.
//
// 32 bytes from crypto/rand. Not math/rand, and not a UUID: a v4 UUID carries
// 122 bits and is generated by libraries with varying opinions about entropy
// sources, which is not a thing to be casual about for the credential that
// provisions door hardware.
func generateSiteKey() (key, hash, prefix string, err error) {
	raw := make([]byte, 32)
	if _, err := rand.Read(raw); err != nil {
		return "", "", "", fmt.Errorf("generating site key: %w", err)
	}

	key = siteKeyPrefix + hex.EncodeToString(raw)
	hash = HashSiteKey(key)
	prefix = key[:12] // non-secret, for logs and admin display
	return key, hash, prefix, nil
}

// HashSiteKey returns the stored form of a site credential.
//
// Exported because the authentication path hashes what a caller presented
// before looking it up, and that has to be the same function that produced the
// stored value. Two spellings of "the hash" is how an authentication system
// stops authenticating.
func HashSiteKey(key string) string {
	sum := sha256.Sum256([]byte(key))
	return hex.EncodeToString(sum[:])
}

// SiteCredential is a freshly minted key, returned ONCE.
//
// Key is populated only by CreateSite and RotateSiteAPIKey. Nothing else in this
// package can produce one, because nothing else knows it.
type SiteCredential struct {
	Key    string
	Prefix string
}

// NewSite is the input to CreateSite.
type NewSite struct {
	Name     string
	Address  string
	Timezone string
}

// CreateSite creates a site inside a company and issues its provisioning key.
//
// The key is returned in the SAME call that creates the site and never again --
// the database holds only its hash. That is the same shape RegisterDevice uses
// for device keys, and for the same reason: the credential is committed the
// moment this succeeds, so a caller that fails afterwards has no way to learn
// what it was.
//
// Name uniqueness is per company and enforced by a partial unique index that
// ignores soft-deleted rows, so a retired site's name can be reused. A conflict
// surfaces as ErrSiteNameTaken rather than as a raw driver error.
func CreateSite(companyID int64, in NewSite) (*models.ConsoleSite, *SiteCredential, error) {
	name := strings.TrimSpace(in.Name)
	if name == "" {
		return nil, nil, models.ErrSiteNameRequired
	}
	if len(name) > 100 {
		return nil, nil, models.ErrSiteNameTooLong
	}

	timezone := strings.TrimSpace(in.Timezone)
	if timezone == "" {
		// Matches the column default. A site whose zone is unknown is better
		// described as UTC than as the API server's incidental location.
		timezone = "UTC"
	}

	key, hash, prefix, err := generateSiteKey()
	if err != nil {
		return nil, nil, err
	}

	var site models.ConsoleSite
	err = DB.QueryRow(`
		INSERT INTO sites (company_id, site_name, address, timezone,
		                   api_key_hash, api_key_prefix, active)
		VALUES ($1, $2, NULLIF($3, ''), $4, $5, $6, TRUE)
		RETURNING public_id, site_name, COALESCE(address, ''), timezone, active, created_at`,
		companyID, name, strings.TrimSpace(in.Address), timezone, hash, prefix).
		Scan(&site.ID, &site.Name, &site.Address, &site.Timezone, &site.Active, &site.CreatedAt)
	if IsUniqueViolation(err) {
		return nil, nil, models.ErrSiteNameTaken
	}
	if err != nil {
		return nil, nil, err
	}

	// A brand new site has no terminals. Stated rather than left to the zero
	// value so the create response has the same shape as a read.
	site.DeviceCount = 0

	return &site, &SiteCredential{Key: key, Prefix: prefix}, nil
}

// SiteUpdate is the input to UpdateSite. Every field is optional; only what is
// supplied is applied, so a caller correcting an address cannot blank a
// timezone it never mentioned.
type SiteUpdate struct {
	Name     *string
	Address  *string
	Timezone *string
	Active   *bool
}

// UpdateSite changes a site's metadata within one company.
//
// DEACTIVATION IS REACHABLE FROM HERE AND IS NOT THE SAME AS RETIREMENT.
// Setting active=false locks out the site key and every terminal at the site
// immediately -- both AuthMiddleware and DeviceAuthMiddleware refuse an inactive
// site -- but it is fully reversible and destroys nothing. RetireSite is the
// one-way door. Keeping them apart gives an operator a way to stop a site
// without deleting it, which is what "we are closing this depot for a month"
// actually needs.
func UpdateSite(companyID, siteID int64, in SiteUpdate) (*models.ConsoleSite, error) {
	if in.Name != nil {
		name := strings.TrimSpace(*in.Name)
		if name == "" {
			return nil, models.ErrSiteNameRequired
		}
		if len(name) > 100 {
			return nil, models.ErrSiteNameTooLong
		}
		in.Name = &name
	}

	// COALESCE against the parameter rather than building the statement from
	// whichever fields were supplied: one query with a fixed shape is easier to
	// read than a string concatenation, and it cannot lose a filter by accident.
	var site models.ConsoleSite
	err := DB.QueryRow(`
		UPDATE sites
		   SET site_name = COALESCE($3, site_name),
		       address   = COALESCE($4, address),
		       timezone  = COALESCE($5, timezone),
		       active    = COALESCE($6, active),
		       updated_at = CURRENT_TIMESTAMP
		 WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
		 RETURNING public_id, site_name, COALESCE(address, ''), timezone, active, created_at,
		           (SELECT count(*) FROM devices d
		             WHERE d.site_id = sites.id AND d.deleted_at IS NULL)`,
		siteID, companyID, in.Name, in.Address, in.Timezone, in.Active).
		Scan(&site.ID, &site.Name, &site.Address, &site.Timezone,
			&site.Active, &site.CreatedAt, &site.DeviceCount)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, models.ErrSiteNotFound
	}
	if IsUniqueViolation(err) {
		return nil, models.ErrSiteNameTaken
	}
	if err != nil {
		return nil, err
	}
	return &site, nil
}

// RetirementResult reports what a retirement actually did.
type RetirementResult struct {
	// TerminalsRetired is how many devices were soft-deleted along with the
	// site. Reported so a caller can say so rather than leaving an operator to
	// discover it.
	TerminalsRetired int
}

// RetireSite soft-deletes a site AND every terminal at it, in one transaction.
//
// WHY IT CASCADES. A terminal exists at exactly one site; a site row that is
// gone leaves its devices unreachable through every console query (all of them
// join sites and filter deleted_at) while their credentials still
// authenticate -- orphaned hardware that no operator can see and nobody can
// revoke. Cascading is the honest reading of "this location is closed".
//
// WHY IT IS NOT REFUSED WHEN TERMINALS EXIST. Refusing until the site is empty
// sounds safer and is a dead end: there is no console route that removes a
// terminal, so a site with hardware could never be retired at all. Instead the
// count is returned and the caller is required to have said it out loud.
//
// WHAT THIS DOES TO THE FLEET, and a caller must warn about it: every terminal
// at the site stops authenticating immediately, on its own device key as well
// as on the site key, because both middlewares refuse a device whose site is
// gone. A door with a terminal on it will not open by fingerprint afterwards.
// This is one-way through the API -- UpdateSite(active=false) is the reversible
// alternative.
func RetireSite(companyID, siteID int64) (*RetirementResult, error) {
	tx, err := DB.Begin()
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	// The site first, company-scoped, so a site in another tenant is not found
	// rather than being retired.
	var retired int64
	err = tx.QueryRow(`
		UPDATE sites
		   SET deleted_at = CURRENT_TIMESTAMP,
		       active = FALSE,
		       updated_at = CURRENT_TIMESTAMP
		 WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
		 RETURNING id`, siteID, companyID).Scan(&retired)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, models.ErrSiteNotFound
	}
	if err != nil {
		return nil, err
	}

	result, err := tx.Exec(`
		UPDATE devices
		   SET deleted_at = CURRENT_TIMESTAMP,
		       active = FALSE,
		       status = 'DISABLED',
		       updated_at = CURRENT_TIMESTAMP
		 WHERE site_id = $1 AND deleted_at IS NULL`, siteID)
	if err != nil {
		return nil, err
	}
	terminals, err := result.RowsAffected()
	if err != nil {
		return nil, err
	}

	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return &RetirementResult{TerminalsRetired: int(terminals)}, nil
}

// RotateSiteAPIKey issues a new provisioning key and invalidates the old one.
//
// The old key stops working the instant this commits; there is no overlap
// window, because a window is a period during which a credential believed to be
// revoked still provisions hardware.
//
// WHO THIS BREAKS, and a caller must say so before doing it:
//
//   - Any tooling holding the old key. Expected -- that is the point.
//   - Terminals still on the DEPRECATED site-key-plus-serial path. A terminal
//     that has been issued its own device key is unaffected, because that
//     credential is a different secret and is not touched here.
//
// LegacyTerminals counts the devices at this site that have never been issued a
// device key, which is the set that certainly still depends on the site key.
// Returned alongside the new credential so the warning can be specific rather
// than generic.
func RotateSiteAPIKey(companyID, siteID int64) (*SiteCredential, int, error) {
	key, hash, prefix, err := generateSiteKey()
	if err != nil {
		return nil, 0, err
	}

	tx, err := DB.Begin()
	if err != nil {
		return nil, 0, err
	}
	defer tx.Rollback()

	var updated int64
	err = tx.QueryRow(`
		UPDATE sites
		   SET api_key_hash = $3,
		       api_key_prefix = $4,
		       api_key_rotated_at = CURRENT_TIMESTAMP,
		       updated_at = CURRENT_TIMESTAMP
		 WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
		 RETURNING id`, siteID, companyID, hash, prefix).Scan(&updated)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, 0, models.ErrSiteNotFound
	}
	if err != nil {
		return nil, 0, err
	}

	var legacy int
	err = tx.QueryRow(`
		SELECT count(*) FROM devices
		 WHERE site_id = $1 AND deleted_at IS NULL AND api_key_hash IS NULL`,
		siteID).Scan(&legacy)
	if err != nil {
		return nil, 0, err
	}

	if err := tx.Commit(); err != nil {
		return nil, 0, err
	}
	return &SiteCredential{Key: key, Prefix: prefix}, legacy, nil
}

// SiteKeyPrefix returns the non-secret identifying prefix of a site's current
// key, for display beside a rotation control. Empty when the site predates the
// prefix column.
func SiteKeyPrefix(companyID, siteID int64) (string, error) {
	var prefix sql.NullString
	err := DB.QueryRow(`
		SELECT api_key_prefix FROM sites
		 WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL`,
		siteID, companyID).Scan(&prefix)
	if errors.Is(err, sql.ErrNoRows) {
		return "", models.ErrSiteNotFound
	}
	if err != nil {
		return "", err
	}
	return prefix.String, nil
}
